### ISSUE TITLE
Error: Unknown language jade

### ISSUE THREAD

**Issue by adamwong246** [lookback/meteor-emails#12]
seems to be a already known load order issue. https://github.com/meteorhacks/meteor-ssr/issues/22

I'm not sure if this is a bug with `meteor-emails` or with `meteor-ssr`?

**Comment by johanbrook** [comment]
Hi!

This package just passes along the option to choose language to `meteor-ssr`. It's probably something concerning that package. Is including Jade before SSR helping?

**Comment by adamwong246** [comment]
by "before" do you mean the order of the `.meteor/packages` file?

But I tried that and no cigar.

**Comment by johanbrook** [comment]
Perhaps I need to add it as a weak dependency, but in the linked issue thread in meteor-ssr, that doesn't seem to work either?

According to its README:

```
Note: the order in which you add jade and SSR matters! First add jade as a dependency and then SSR, otherwise the jade-compiler can not be located by Meteor.
```

So perhaps you have to manually add Jade first and then this package. Clunky.
