### ISSUE TITLE
Question: Support for {{> someTemplate}} ?

### ISSUE THREAD

**Issue by adamgins** [lookback/meteor-emails#13]
Hi, 

great package!!

is there a way to include other sub-templates within an iteration or do I have to include/inline everything in the `each`?

For example:

```
{{#each someList}}
    {{> someListItem}}
{{/each}}
```

**Comment by johanbrook** [comment]
Hi @adamgins! Thanks a lot.

Sadly, including sub templates isn't possible yet. I'm using the [Meteor SSR](https://github.com/meteorhacks/meteor-ssr/) package for server side rendering of the templates, and it seems that hasn't landed in there yet.
