### ISSUE TITLE
Is this a BUNDLE_PATH issue?

### ISSUE THREAD

**Issue by adamgins** [lookback/meteor-emails#14]
Hi, having an issue running on AWS Opswork... I have not set the BUNDLE_PATH yet (I am just trying to track down the location of the Bundle in the docker image.) 

I see this on the log:

```

May 28 23:55:01 BuzzyDockerTestEnv1-buzzytest1 buzzytest:  /built_app/programs/server/node_modules/fibers/future.js:245 
May 28 23:55:01 BuzzyDockerTestEnv1-buzzytest1 buzzytest:                       throw(ex); 
May 28 23:55:01 BuzzyDockerTestEnv1-buzzytest1 buzzytest:  Error: `libsass` bindings not found. Try reinstalling `node-sass`? 
May 28 23:55:01 BuzzyDockerTestEnv1-buzzytest1 buzzytest:      at Module._compile (module.js:456:26) 
May 28 23:55:01 BuzzyDockerTestEnv1-buzzytest1 buzzytest:      at Object.Module._extensions..js (module.js:474:10) 
May 28 23:55:01 BuzzyDockerTestEnv1-buzzytest1 buzzytest:      at getBinding (/built_app/programs/server/npm/lookback_emails/node_modules/node-sass/lib/index.js:22:11) 
May 28 23:55:01 BuzzyDockerTestEnv1-buzzytest1 buzzytest:      at Object.<anonymous> (/built_app/programs/server/npm/lookback_emails/node_modules/node-sass/lib/index.js:188:23) 
May 28 23:55:01 BuzzyDockerTestEnv1-buzzytest1 buzzytest:      at Module.require (module.js:364:17) 
May 28 23:55:01 BuzzyDockerTestEnv1-buzzytest1 buzzytest:      at Module.load (module.js:356:32) 
May 28 23:55:01 BuzzyDockerTestEnv1-buzzytest1 buzzytest:      at Function.Module._load (module.js:312:12) 
May 28 23:55:01 BuzzyDockerTestEnv1-buzzytest1 buzzytest:      at require (module.js:380:17) 
May 28 23:55:01 BuzzyDockerTestEnv1-buzzytest1 buzzytest:      at __coffeescriptShare (packages/lookback:emails/utils.coffee:5:12) 
```

**Comment by johanbrook** [comment]
Hi. I'm also seeing this in the last release (0.4.1). Try using 0.4.0. I'm not sure of what's gone wrong, since 0.4.1 was completely unrelated to any `node-sass` stuff. 

Googling the error just suggests reinstalling `node-sass`. I should update to the latest `node-sass`, but need to ensure compability and those things.

Sorry for the hassle. Hope 0.4.0 will do.

**Comment by adamgins** [comment]
@johanbrook thanks... I am actually using   0.4.0 in my local meteor project. Any other ideas?

Update:... uh my mistake, I was using 0.4.0 locally.. I just updated to hardcode the 0.4.0 version... will try it soon.

Update - yep, working on 0.4.0 - thanks

**Comment by adamgins** [comment]
I have set the environment variable BUNDLE_PATH to `/built_app` see errors above, that looks like the right path, does that look correct? (I am using the meteord docker based system to this is all automated for me) see this thread https://forums.meteor.com/t/aws-opsworks-meteor-docker-deployment/1937/61 and the error above seems to say that I have set it correctly.

**Comment by adamgins** [comment]
Mmm.. perhaps the docker process is installing 0.4.1 as I just upgraded my local version to 0.4.1 and I am getting the issue. 

I tried removing the package and then readding 0.4.0 and I get the following error:

```
$ meteor remove lookback:emails@=0.4.0
lookback:emails@=0.4.0: do not specify version constraints.

```

**Comment by adamgins** [comment]
closing this as covered in https://github.com/lookback/meteor-emails/issues/15
