### ISSUE TITLE
0.4.1 crashes on startup: libsass bindings not found

### ISSUE THREAD

**Issue by johanbrook** [lookback/meteor-emails#15]
As of 0.4.1, this error is thrown:

```
Error: `libsass` bindings not found. Try reinstalling `node-sass`?
```

According to google, people usually reinstall `node-sass` to solve this. I'm not sure why the error came in 0.4.1, since that release didn't touch any dependencies at all.

I could look into upgrading to latest `node-sass` (0.3.x).

**Comment by adamwong246** [comment]
+1

**Comment by satyavh** [comment]
+1

Got the same issue. Downgraded to 0.4.0 and which works fine.

**Comment by meichenblatt** [comment]
+1

**Comment by meichenblatt** [comment]
I downgraded but I'm still getting the error :(

**Comment by johanbrook** [comment]
@meichenblatt @satyavh @adamwong246 Is https://github.com/lookback/meteor-emails/pull/21 building okay for you locally?

**Comment by satyavh** [comment]
I'd love to test, but not very experienced with building locally. If you can tell me how I will test

**Comment by johanbrook** [comment]
@satyavh Just checkout the `fix/libsass-bindings` branch locally in your `packages` directory (create it if not exists).

```
cd packages
git clone git@github.com:lookback/meteor-emails.git lookback:emails
git fetch origin
git checkout origin/fix/libsass-bindings
```

**Comment by satyavh** [comment]
I see you merged that already in 0.4.2. I can't get it to work locally, and I can't install 0.4.2, it gives me:
"No compatible binary build found for this package" on OSX, latest meteor. Please contact the package author" 

I'm sticking with 0.4.0 for now :-)

---

When I build locally:

```
pm ERR! Error: EACCES, mkdir '/Users/satya/.npm/minimist/1.1.1'
npm ERR!  { [Error: EACCES, mkdir '/Users/satya/.npm/minimist/1.1.1']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/Users/satya/.npm/minimist/1.1.1',
npm ERR!   parent: 'meow' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Darwin 14.0.0
npm ERR! command
"/Users/satya/.meteor/packages/meteor-tool/.1.1.3.1ekqsng++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
"/Users/satya/.meteor/packages/meteor-tool/.1.1.3.1ekqsng++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm" "install"
"node-sass@3.2.0"
npm ERR! cwd /Users/satya/Development/meteor-packages/lookback:emails/.npm/package-new-1xru2zs
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! path /Users/satya/.npm/minimist/1.1.1
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, mkdir '/Users/satya/.npm/minimist/1.1.1'
npm ERR! not ok code 0

 => Errors while adding packages:

While building package satya:emails:
error: couldn't install npm package
```

**Comment by johanbrook** [comment]
Yep, it's due to https://github.com/lookback/meteor-emails/issues/23. I have no idea why the build fails on the OS X build machine.

**Comment by johanbrook** [comment]
Updated README: https://github.com/lookback/meteor-emails/commit/3f2f0ce3f4223c49ac1bf9624db288738cfe7a07

**Comment by johanbrook** [comment]
Fixed by https://github.com/lookback/meteor-emails/commit/39a6520417ed93d3f483cb15e155fa5b85830fa0, published as v0.4.3.

**Comment by nloui** [comment]
Still seem to be having this issue with the correct env variable set.

**Comment by johanbrook** [comment]
@nloui Have you tried the latest version?

**Comment by nloui** [comment]
@johanbrook yup, no good still unfortunately
