### ISSUE TITLE
Modulus support?

### ISSUE THREAD

**Issue by adamwong246** [lookback/meteor-emails#16]
I am unable to get this package running on modulus. While I can set environmental variables, the actual path is subject to change and I have yet to uncover a method for exposing the path.

**Comment by jadsonlourenco** [comment]
@adamwong246 if you restart the app after add this env variable? I use Dokku and get an error like this, after "rebuild" the app works fine.

**Comment by adamwong246** [comment]
Do you mean the `BUNDLE_PATH` environment variable? And if so, what value did you set?

**Comment by adamwong246** [comment]
I was able to fix this by using the `process.env.APP_DIR` variable, as per http://help.modulus.io/customer/en_us/portal/questions/12745491--dirname?new=12745491

https://github.com/lookback/meteor-emails/pull/17
