### ISSUE TITLE
sharing assets?

### ISSUE THREAD

**Issue by adamwong246** [lookback/meteor-emails#19]
I'd really prefer that my client styles and my email styles be one and the same. Is this impossible? Moving  my client/scripts to the root of the projects didn't work.

**Comment by johanbrook** [comment]
@adamwong246 Thing is we wanna read the CSS file from fisk (see https://github.com/lookback/meteor-emails/blob/master/emails.coffee#L123), and since Meteor is bundling up all client CSS, we can't reach it. Hence, it needs to live in `private`.
