### ISSUE TITLE
No compatible build found for version 0.3.2

### ISSUE THREAD

**Issue by hvtor** [lookback/meteor-emails#2]
Received an error when adding version 0.3.2.

=> Errors while adding packages:

While checking for lookback:emails@0.3.2:
error: No compatible build found

:+1: meteor add lookback:email@=0.3.1

:-1: meteor add lookback:email@=0.3.2

**Comment by johanbrook** [comment]
Hi @hvtor, thanks for reporting. What OS are you on? Meteor version? I've got issues publishing this package for Windows (see https://github.com/lookback/meteor-emails/issues/1) just today, and it might be related. Please use `0.3.1` for now. That version should be built for *nix platforms.

_Edit:_ Should work now, I re-published `0.3.2` for all platforms (except Windows).

**Comment by hvtor** [comment]
Hi @johanbrook I'm using Mac OS 10.10.1, Meteor 1.0.5. 

Thanks 0.3.2 is working now :)

Is there an existing example app? Having trouble with setup.

**Comment by johanbrook** [comment]
Great.

I'll provide an example app.
