### ISSUE TITLE
Don't use node-sass as a hard dependency

### ISSUE THREAD

**Issue by johanbrook** [lookback/meteor-emails#22]
Idea from @jadsonlourenco in https://github.com/lookback/meteor-emails/issues/10#issuecomment-105287109. 

I don't know if it's possible to do a conditional `Npm.depends` call though – weak dependencies are only available for Meteor packages.

**Comment by jadsonlourenco** [comment]
Well, I tested the new version (0.4.6) and works fine, now don't have the SASS compiler by default, don't get any error when running the "bundle" version like before. **Thank you!**

PS: You know that the new Meteor 1.2 will have a better support to compile the SASS/LESS/STYLUS without packages, I think, I will read more about and then back, maybe it can help us to have this compilers without problems. I mean, all in same time.

**Comment by johanbrook** [comment]
@jadsonlourenco Hm, weird – I removed Sass as hard dep in v0.5.0, in https://github.com/lookback/meteor-emails/pull/35 :) But good thing it works anyway.

> You know that the new Meteor 1.2 will have a better support to compile the SASS/LESS/STYLUS without packages

Yep, I think things will be a tad easier, at least.
