### ISSUE TITLE
Mailer.init() results in Error: Match error: Expected object, got undefined 

### ISSUE THREAD

**Issue by hvtor** [lookback/meteor-emails#3]
Meteor.startup(function() {
        Mailer.init();
        Mailer.config(
        {
          from: 'Name name@domain.com',  
          replyTo: 'Name name@domain.com', 
          routePrefix: 'emails',  
          baseUrl: process.env.ROOT_URL,  
          testEmail: null,  
          logger: console  
        }  
    ); // Mailer.config
}); // Meteor.startup

So it appears the app is crashing, and works when I remove Mailer blocks.

So what would be a solution to this issue?  

Thank you for any and all help you can provide.
~ Hemant 

Here is the error I see in the console:
W20150326-07:51:43.149(-4)? (STDERR) Error: Match error: Expected object, got undefined
W20150326-07:51:43.149(-4)? (STDERR)     at checkSubtree (packages/check/match.js:275:1)
W20150326-07:51:43.149(-4)? (STDERR)     at check (packages/check/match.js:32:1)
W20150326-07:51:43.149(-4)? (STDERR)     at MailerClass (packages/lookback:emails/emails.coffee:65:3)
W20150326-07:51:43.149(-4)? (STDERR)     at Object.Mailer.init (packages/lookback:emails/emails.coffee:392:12)
W20150326-07:51:43.149(-4)? (STDERR)     at Meteor.publishComposite.filter (app/server/server.js:32:9)
W20150326-07:51:43.149(-4)? (STDERR)     at /Users/hvt/premeteor/.meteor/local/build/programs/server/boot.js:229:5

**Comment by johanbrook** [comment]
`Mailer.init()` expects a config object, with a `templates` key at least, as outlined in the README: https://github.com/lookback/meteor-emails#api.

You can have the `Mailer.config()` call anywhere in your code, but the `Mailer.init()` code should preferrable be inside of a `Meteor.startup` call.

**Comment by hvtor** [comment]
Having some issues with syntax and setup.  

I've placed the Mailer.init() inside of a Meteor.startup call as follows:

```
      Mailer.init({
        templates: 'emails/unitsEmail/sendUnitsTwo',      
            helpers: 'sendUnits',
        layout: false
});
```

I began with files in a folder called Client/emails/unitsEmail/

I have placed my template and js files in the server folder (which I think doesn't make sense for access to Templates/helpers)

server/templates/sendUnitsTwo.js <--- helper called 'sendUnits'
server/templates/sendUnitsTwo.html <--- {{ sendUnits }}
server/templates/sendUnitsTwo.css

Getting an error regarding the helper:
Template.sendUnitsTwo.helpers({
    sendUnits: function() {
        var propertyId = this.params._id;  
                 var propertyId = this._id;
        console.log(propertyId);
        return Units.findOne({_id: propertyId});  
    }
});

Router.route('/properties/:_id/unitsEmail', function () {
  this.render('emails/unitsEmail/sendUnitsTwo');
  },
  {
  data  : function () { 
    return [Properties.findOne({_id: this.params._id}), Units.find({propertyId: this.params._id}).fetch()];
  }
});

Just getting some strange errors.

Is there an example project that I can reference ?

**Comment by johanbrook** [comment]
Please refer to the README for the API :) 

For instance, the `templates` option sent to `Mailer.init` should be **an object** as well – right now, you've set it to a string.

Also, this runs on the **server**, so it won't work with client templates.

Read the README for full explanations.

**Comment by hvtor** [comment]
I've read the API, but I'm finding conflicting issues when I attempt what is recommended.

I've tried both methods, setting the KV as an object, and as a string (which you told me was the wrong way of doing this) despite the documentation suggesting otherwise. Here is how the API suggests Mailer.send(Object) be treated: 

Takes a plain object with the following properties:

{
  to: 'Name name@domain.com',           // 'To: ' address. Required.
  subject: 'Subject',                     // Required.
  template: 'templateName',               // Required.
  replyTo: 'Name name@domain.com',      // Override global 'ReplyTo: ' option.
  from: 'Name name@domain.com',         // Override global 'From: ' option.
  data: {}                                // Optional. Render your email with a data object.
}

I am getting errors with Mailer.init() using the Object notation you suggested pertaining to the templates option. The following syntax is displayed in the API documentation:

Mailer.init(Object). Kick things off with runtime settings!

Takes a plain object with the following properties:

{
  templates: {},        // Required. A key-value hash where the keys are the template names. See more below.
  helpers: {},          // Global helpers available for all templates.
  layout: false         // Global layout template.
}

However, when I set it to the Object syntax you suggested, I am seeing errors pertaining to the curly braces.  Here is what I currently have in server/server.js:

Mailer.init({
        templates: {'server/emails/sendUnitsTwo'},
        helpers: {'sendUnits'}, 
        layout: false
    });

A published example app in Meteor would be great.  Would you be so kind as to publish it?  Thank you in advance.  I am eager to figure this out, and I'd be happy to share my app with you if that would be helpful.

**Comment by johanbrook** [comment]
@hvtor Seems you're not writing valid Javascript in your provided code:

``` js
Mailer.init({
   templates: {'server/emails/sendUnitsTwo'},  // This isn't even valid JS!
   helpers: {'sendUnits'}, // Neither is this.
   layout: false
});
```

But I've also created a sample app [here](https://github.com/lookback/meteor-emails/tree/master/example) which you can consult.

**Comment by hvtor** [comment]
@johanbrook I greatly appreciate the pointers. I'll follow your sample app.

Thanks for the help!
