### ISSUE TITLE
I upgraded from 0.4.0 to 0.4.5 and I get "Exited with code: 1"

### ISSUE THREAD

**Issue by adamgins** [lookback/meteor-emails#32]
Sorry, I don't seem to have more info. If I re-install 0.4.0 it all works.
Were there breaking changes in code between those versions?

**Comment by johanbrook** [comment]
@adamgins Is this still popping up for you?

**Comment by adamgins** [comment]
@johanbrook yep. I had upgraded to 0.4.5 , have not checked since..

**Comment by johanbrook** [comment]
I can't reproduce this. So weird. 

So there's no stack trace or anything?

**Comment by adamgins** [comment]
I can't see anything on the sever console. Is there some other log file /setting so I can get more detail?

**Comment by todda00** [comment]
I'm using 0.4.5:
I have just started to use this package, and it works locally, but when I try to deploy it to a AWS E2 instance via Meteor Up, I get the following error log: 

```
-----------------------------------STDERR-----------------------------------
    ms/server/npm/chrisbutler_node-sass/node_modules/node-sass',
    gyp info spawn args   '--depth=.',
    gyp info spawn args   '--no-parallel',
    gyp info spawn args   '--generator-output',
    gyp info spawn args   'build',
    gyp info spawn args   '-Goutput_dir=.' ]
    gyp: name 'libsass_ext' is not defined while evaluating condition 'libsass_ext == "" or libsass_ext == "no"' in binding.gyp while trying to load binding.gyp
    gyp ERR! configure error 
    gyp ERR! stack Error: `gyp` failed with exit code: 1
    gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/node-gyp/lib/configure.js:355:16)
    gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
    gyp ERR! System Linux 3.13.0-46-generic
    gyp ERR! command "node" "/usr/bin/node-gyp" "rebuild"
    gyp ERR! cwd /opt/staging-cc/tmp/bundle/programs/server/npm/chrisbutler_node-sass/node_modules/node-sass
    gyp ERR! node -v v0.10.36
    gyp ERR! node-gyp -v v2.0.1
    gyp ERR! not ok 
    -----------------------------------STDOUT-----------------------------------
    => re-installing binary npm module 'node-sass' of package 'chrisbutler_node-sass'
    ----------------------------------------------------------------------------
```

**Comment by johanbrook** [comment]
Hm, `node-sass` is acting up again. I should probably make SCSS compiling opt-in, since it causes so much trouble. That seems like a lowlevel libsass error.

Have you any idea of this, @chrisbutler ?

**Comment by todda00** [comment]
opt-in SASS would be great, I really just want a few basic templates, I can go through the pain of writing old school CSS for a few emails.

**Comment by chrisbutler** [comment]
@adamgins can you give us more info on your system?

@todda00 it's working for me using mupx on ubuntu 14.04.2

can you guys remove the emails package and just try installing `chrisbutler:node-sass` and see what happens?

@johanbrook making it somehow optional does seem ideal... but you'd probably have to do it as an addon package, like `lookback:emails-sass` or something?

**Comment by adamgins** [comment]
@chrisbutler 
this is just my local dev environment on OSX Yosemite. Running Meteor 1.1.0.2 
everything seems to work fine with 0.4.0 version. From memory, this issue started with 0.4.1 and I just stuck with 0.4.0.
is there some way I can get debugging turned on to get more info?

**Comment by johanbrook** [comment]
> is there some way I can get debugging turned on to get more info?

@adamgins This package is set to be verbose as default (see [this line](https://github.com/lookback/meteor-emails/blob/master/emails.coffee#L22)), so that should be all info we got so far.

> making it somehow optional does seem ideal... but you'd probably have to do it as an addon package, like lookback:emails-sass or something?

@chrisbutler Cannot something with weak dependencies be set up? For instance, detect that your SCSS package exists and load after it, and in code detect SCSS support.

**Comment by todda00** [comment]
@chrisbutler 

I do not have the emails package installed anymore, I add chrisbutler:node-sass only, and try to deploy with the same resulting error:

```
    -----------------------------------STDERR-----------------------------------
    ms/server/npm/chrisbutler_node-sass/node_modules/node-sass',
    gyp info spawn args   '--depth=.',
    gyp info spawn args   '--no-parallel',
    gyp info spawn args   '--generator-output',
    gyp info spawn args   'build',
    gyp info spawn args   '-Goutput_dir=.' ]
    gyp: name 'libsass_ext' is not defined while evaluating condition 'libsass_ext == "" or libsass_ext == "no"' in binding.gyp while trying to load binding.gyp
    gyp ERR! configure error 
    gyp ERR! stack Error: `gyp` failed with exit code: 1
    gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/node-gyp/lib/configure.js:355:16)
    gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
    gyp ERR! System Linux 3.13.0-46-generic
    gyp ERR! command "node" "/usr/bin/node-gyp" "rebuild"
    gyp ERR! cwd /opt/staging-cc/tmp/bundle/programs/server/npm/chrisbutler_node-sass/node_modules/node-sass
    gyp ERR! node -v v0.10.36
    gyp ERR! node-gyp -v v2.0.1
    gyp ERR! not ok 
    -----------------------------------STDOUT-----------------------------------
    => re-installing binary npm module 'node-sass' of package 'chrisbutler_node-sass'
    ----------------------------------------------------------------------------
```

**Comment by todda00** [comment]
when I remove the chrisbutler:node-sass package it deploys perfectly.

**Comment by chrisbutler** [comment]
@todda00 can you update your node version?

**Comment by todda00** [comment]
@chrisbutler Well meteor is stuck on node 0.10.X, so I upgraded it to 0.10.40 and got the same error.

**Comment by chrisbutler** [comment]
@todda00 there are some known/ongoing issues with node-sass. can you try following the suggestions here and see what you come up with? https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md

**Comment by todda00** [comment]
@chrisbutler the node-sass installs OK when I install it directly on the server via `sudo npm install -g node-sass` but the deploy still fails.

The only way I was able to get this to work was to install sass on the server via gems, and pull in the lookback:meteor-email package locally and remove chrisbutler:node-sass from package.js

**Comment by johanbrook** [comment]
@todda00 @chrisbutler I've removed `node-sass` as a hard dep in here: https://github.com/lookback/meteor-emails/pull/35. Feel free to pull it down and test.

**Comment by adamgins** [comment]
@johanbrook I found the issue. I had a rogue `</a>` buried deep in a template. For some reasons 0.4.0 did not complain about this... subsequent version just `exited`. 

Wondering if we could have some better error logging, please?

**Comment by johanbrook** [comment]
@adamgins Gotcha, I should take care of badly formatted templates better. Thanks!
