### ISSUE TITLE
Exit code 8 when updating from 0.4.3 to 0.4.4 and 0.4.5

### ISSUE THREAD

**Issue by vhuerta** [lookback/meteor-emails#33]
Hi, Im getting this error when i update the package from version 0.4.3 to 0.4.4 and 0.4.5

W20150812-10:02:17.051(-5)? (STDERR)
W20150812-10:02:17.053(-5)? (STDERR) /Users/bc/.meteor/packages/meteor-tool/.1.1.4.1a6rm8b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150812-10:02:17.053(-5)? (STDERR)                        throw(ex);
W20150812-10:02:17.053(-5)? (STDERR)                              ^
W20150812-10:02:17.053(-5)? (STDERR) Error: Match error: Failed Match.OneOf or Match.Optional validation in field layout
W20150812-10:02:17.053(-5)? (STDERR)     at checkSubtree (packages/check/match.js:244:1)
W20150812-10:02:17.053(-5)? (STDERR)     at packages/check/match.js:296:1
W20150812-10:02:17.053(-5)? (STDERR)     at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
W20150812-10:02:17.053(-5)? (STDERR)     at checkSubtree (packages/check/match.js:290:1)
W20150812-10:02:17.054(-5)? (STDERR)     at check (packages/check/match.js:32:1)
W20150812-10:02:17.054(-5)? (STDERR)     at compile (packages/lookback:emails/emails.coffee:101:5)
W20150812-10:02:17.054(-5)? (STDERR)     at packages/lookback:emails/emails.coffee:384:9
W20150812-10:02:17.054(-5)? (STDERR)     at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
W20150812-10:02:17.054(-5)? (STDERR)     at init (packages/lookback:emails/emails.coffee:381:9)
W20150812-10:02:17.054(-5)? (STDERR)     at MailerClass (packages/lookback:emails/emails.coffee:390:3)
=> Exited with code: 8

**Comment by johanbrook** [comment]
@vhuerta Hi! Sorry for late reply. Did you call the package with the correct arguments?

**Comment by vhuerta** [comment]
Im using this:

``` javascript
Mailer.init({
templates: {
        resetPassword: {
            path: 'email/reset_email/template.html',
            layout: 'emailLayout',
            route: {
                path: '/resetPassword/:name',
                data: function() {
                    return {
                        background: Accounts.urls.backgroundUrl(),
                        logo: Accounts.urls.logoUrl(),
                        icon: Accounts.urls.iconMailUrl(),
                        user: "Ricardo Martinez Perez de Leon",
                        resetPasswordUrl: "http://127.0.0.1:3000/password_reset/123",
                        year: function() {
                            var now = new Date();
                            return now.getFullYear();
                        }
                    }
                }
            }
        }
    },
    layout: {
        name: 'emailLayout',
        path: 'email/layout.html'
    }
});
```

**Comment by johanbrook** [comment]
@vhuerta Can you try out the latest version of this package as well?

**Comment by vhuerta** [comment]
Still getting this, every version up 0.4.3

W20151012-15:27:58.653(-5)? (STDERR) /Users/vhuerta/.meteor/packages/meteor-tool/.1.1.9.1sd3e7j++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20151012-15:27:58.653(-5)? (STDERR)                        throw(ex);
W20151012-15:27:58.653(-5)? (STDERR)                              ^
W20151012-15:27:58.653(-5)? (STDERR) Error: Match error: Failed Match.OneOf or Match.Optional validation in field layout
W20151012-15:27:58.654(-5)? (STDERR)     at checkSubtree (packages/check/match.js:244:1)
W20151012-15:27:58.654(-5)? (STDERR)     at packages/check/match.js:296:1
W20151012-15:27:58.654(-5)? (STDERR)     at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
W20151012-15:27:58.654(-5)? (STDERR)     at checkSubtree (packages/check/match.js:290:1)
W20151012-15:27:58.654(-5)? (STDERR)     at check (packages/check/match.js:32:1)
W20151012-15:27:58.655(-5)? (STDERR)     at compile (packages/lookback_emails/emails.coffee:107:5)
W20151012-15:27:58.655(-5)? (STDERR)     at packages/lookback_emails/emails.coffee:356:9
W20151012-15:27:58.655(-5)? (STDERR)     at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
W20151012-15:27:58.655(-5)? (STDERR)     at init (packages/lookback_emails/emails.coffee:353:9)
W20151012-15:27:58.655(-5)? (STDERR)     at MailerClass (packages/lookback_emails/emails.coffee:362:3)
=> Exited with code: 8

**Comment by johanbrook** [comment]
@vhuerta The `layout` field for a template takes an object or boolean, you've provided a string. I've clarified the documentation on this: https://github.com/lookback/meteor-emails#layouts.

Please note that if you set the `layout` globally, as you've done, there's no need to specify it again for that specific template. If you do, send an object with `name` and `path` keys. 

Let me know how that works out!

(Please note that latest version is 0.5.1).

**Comment by vhuerta** [comment]
Great i remove the layout from the resetPassword template and now its working fine in version 0.5.x thanks for the help
