### ISSUE TITLE
Use Assets.getText?

### ISSUE THREAD

**Issue by hellogerard** [lookback/meteor-emails#4]
Why bother with `BUNDLE_PATH` and `path.join`?  Am I missing something or can you not just use [Assets.getText()](http://docs.meteor.com/#/full/assets_getText) to find email templates in the `private` folder?

**Comment by hellogerard** [comment]
Nevermind. Found the answer. Knew there had to be a reason. `Assets.getText` does not work from within packages (see https://github.com/meteor/meteor/issues/1382). It only works if the assets have already been added via `addFiles` in `package.js`. 

My underlying problem is that, on Modulus, the absolute app path can change upon restart or deploy. So then, every time I deploy, I have to watch for the absolute path, and then if it changes, change the BUNDLE_PATH, and then restart the app. BTW, restarting the app could potentially change the app path again.

I wonder if the `template` config object could take a string or a filepath. If it takes a string, then I could read my email templates myself with `Assets.getText` and then pass in the string.

**Comment by johanbrook** [comment]
@hellogerard 

Hi, sorry for seeing this "too late", so to speak. Your question was very valid, and I had to think a while to remember why I took the route I did (but it was because of the reason you described).

> BTW, restarting the app could potentially change the app path again.

Are you sure? When I deploy a Meteor app bundle, I put it in a specific path (the `BUNDLE_PATH`) and start it with `forever`. That path is static. May depend on setup though.

> I wonder if the template config object could take a string or a filepath. If it takes a string, then I could read my email templates myself with Assets.getText and then pass in the string.

Valid. I'll give it some thinking. Thanks!

**Comment by hellogerard** [comment]
Yes, regarding `BUNDLE_PATH` changing, it's only on Modulus, probably because it's a PaaS-type setup. I imagine the path does not change if you're using MUP on your own server or something like that.

**Comment by adamwong246** [comment]
+1 would really like a better way to use this package on modulus.

**Comment by johanbrook** [comment]
I agree with you both, but this is a constraint in getting a hold of a file server side when deployed. I'm all open for ideas.

An alternative could be @hellogerard's idea about just sending the whole HTML string as a template. Wouldn't make too much difference if the package or user stringifies the template.

**Comment by adamwong246** [comment]
is there any hope of accessing the `__dirname` on modulus? http://help.modulus.io/customer/portal/articles/1653448-file-storage
