### ISSUE TITLE
Preview doesn't work since upgrading from 0.4.0 to 0.5.1

### ISSUE THREAD

**Issue by satyavh** [lookback/meteor-emails#40]
I got a route setup like this:

```
  route:
    path: '/invite/:email',
```

so this should show preview, which it always did in `v0.4.0` that I was using before.

`http://localhost:3050/emails/preview/invite/email@example.com`

But it now keeps loading forever (pending) with no server/console errors. 
I'm on latest `1.0.12` Iron Router

**Comment by johanbrook** [comment]
Hm, I cannot reproduce this in the `example` app. Can you reproduce it in a separate, vanilla Meteor app? (I tried example app with Meteor 1.2).

**Comment by satyavh** [comment]
Ok I figured this out. Damn Iron Router, that router is so tricky. 

I actually switched to Flow Router for all my Meteor projects, so I'm planning at some time to make your package compatible with FR as well (using meteorhacks:picker until Flow Router 3.0 will be released). Would you be interested in that?

**Comment by johanbrook** [comment]
@satyavh Great.

I actually would like to move away from any router at all, and use Meteor's built in `WebApp.connectHandlers`, if possible. PR for that is encouraged, of course.

**Comment by satyavh** [comment]
Even better, but I haven't used the WebApp api yet so can't help there.

I was also thinking, it might be interesting to automatically add routes to 'view this message in a browser'. Then when you enable that feature, you get a helper that you can include in your template. That helper links to a route that shows that message in the browser. Now you probably don't want to do that based on an email address for security reasons, so it should fetch it based on some hash. Which means the package needs to store the email address-template-hash relation. Doesn't sound to complicated though.

**Comment by johanbrook** [comment]
Sounds cool, I'll create a new issue for it. 

Skickat från min iPhone
