### ISSUE TITLE
How to include images from assets (public/private) in an email template?

### ISSUE THREAD

**Issue by satyavh** [lookback/meteor-emails#41]
Can't figure this out (except hosting externally). Any tips?

**Comment by johanbrook** [comment]
@satyavh Just reference them by their absolute path. You can use the built-in template helper `baseUrl` for that: http://lookback.github.io/meteor-emails/docs/emails.html#section-6:

``` html
<img src="{{ baseUrl '/images/image.png' }}">
```

**Comment by satyavh** [comment]
Aha, thanks a lot for that.
