### ISSUE TITLE
Routes are created in production

### ISSUE THREAD

**Issue by satyavh** [lookback/meteor-emails#43]
When I try to access the `preview` / `send` routes in production, they are accessible but the response is:

`Couldn't find a template named "notfound" or "notfound". Are you sure you defined it?`

I think this is not secure enough. Those routes should not exist at all so something goes wrong here.

**Comment by johanbrook** [comment]
Are you sure? Check out this line: https://github.com/lookback/meteor-emails/blob/master/emails.coffee#L359. The routes should not be added unless `process.env.NODE_ENV === 'development'`. It seems your Meteor app gets a 404, and then tries to render a non-existing template `notFound`.

**Comment by satyavh** [comment]
argh, you're completely right! Sorry man!

**Comment by johanbrook** [comment]
No worries :)
