### ISSUE TITLE
nesting templates/defining templates with tags

### ISSUE THREAD

**Issue by chrisbutler** [lookback/meteor-emails#5]
hey guys, this is a great package and so far it's making life so much easier. i have some templates and helpers client side that render a data table:

```
<template name="Status">
  <div class="status">
    {{> dataTable}}
  </div>
</template>

<template name="dataTable">
  <div class="data-block">
    <table class="ui table">
      <thead>
        <tr>
          {{#each headings}}
            <th>
              {{{this}}}
            </th>
          {{/each}}
        </tr>
      </thead>
      <tbody>
        {{#each tanks}}
          <tr>
            {{> tableRow data=this}}
          </tr>
        {{/each}}
      </tbody>
    </table>
  </div>
</template>

<template name="tableRow">
  {{#each data}}
    <td>{{this}}</td>
  {{/each}}
</template>
```

I would like to be able to re-use the same templates to render the data on the client and in emails... to use the same markup but different css. Right now I've duplicated that code and refactored it into a single template to use in my email: 

```
<div class="data-block">
  <table class="ui table">
    <thead>
      <tr>
        {{#each headings}}
          <th>
            {{{this}}}
          </th>
        {{/each}}
      </tr>
    </thead>
    <tbody>
      {{#each tanks}}
        <tr>
          {{#each this}}
            <td>{{this}}</td>
          {{/each}}
        </tr>
      {{/each}}
    </tbody>
  </table>
</div>
```

but i would like to be able to just do:

```
<div class="data-block">
    {{> dataTable}}
</div>
```

but it doesn't find the template if i put it in the same file... and i don't know where else it could go. thoughts on this?

**Comment by johanbrook** [comment]
Thanks! We're using the [`meteor-ssr`](https://github.com/meteorhacks/meteor-ssr) package for rendering the templates on the server, and as far as I can see, it doesn't support template inclusions à la

```
<template name="foo">
   {{ > anotherTemplate }}
</template>
```

Feel free to check out that package for any leads.

But since templates for emails need to live in the `private` directory anyway, it might be tricky to reach the point where you can share templates between client and server without additional work :/ Sorry about that.

**Comment by chrisbutler** [comment]
hey @johanbrook, thanks for the feedback. it looks like @arunoda was at one point loading client side templates (https://github.com/meteorhacks/meteor-ssr/blob/03d19696dc93ea531f8cf2864613a5bc756eabb7/lib/core.js#L6) but that has since been removed. i'm going to poke around a bit and see if i can use that as a guide to integrate the functionality here

**Comment by johanbrook** [comment]
Cool! Good luck.
