### ISSUE TITLE
Support array of 'to' addresses

### ISSUE THREAD

**Issue by chrisknu** [lookback/meteor-emails#55]
The validator is checking incoming 'to' field as a string, wherein the meteor docs support string or array of strings.

Behaviour should be the same

http://docs.meteor.com/#/full/email_send

**Comment by johanbrook** [comment]
Agreed. PR appreciated.

**Comment by johanbrook** [comment]
Fixed in https://github.com/lookback/meteor-emails/commit/d441cc621e03aca90e3acb7d161b2554afc85c76.

**Comment by chrisknu** [comment]
Thanks!
