### ISSUE TITLE
Advice re. Meteor 1.3

### ISSUE THREAD

**Issue by flippyhead** [lookback/meteor-emails#58]
Hi thanks so much for this fantastic project. 

We're using Meteor 1.3 which has module support. Do you have any recommendations on how to best use `meteor-emails` in this new setup?

Thanks!

**Comment by johanbrook** [comment]
Hi! Thanks for the warm words.

I haven't tried this package in a 1.3 setup yet, and I'd like to support both pre-1.3 and modules. It might be easily achievable, but I haven't tried yet.

Feel free to play around with this in a 1.3 app and report back with any issues.

**Comment by flippyhead** [comment]
`meteor-emails` works great under 1.3 as MDG has taken pains to ensure backwards compatibility. The main thing is the reliance on global objects and how you are doing paths to things in `Templates`. We'll try out a few things but it seems like there should be a different pattern that lets you import templates declaratively, keeping everything in the new `imports` folder.

**Comment by johanbrook** [comment]
I see, thanks!

Well, you don't _have_ to use globals in 1.3 if you don't want to. You could for example take this approach:

``` js
import {myEmailTemplate, anotherTemplate} from './templates.';

Mailer.init({
   templates: {myEmailTemplate, anotherTemplate}
});
```

`lookback:emails` doesn't care _how_ you provide the `template` hash.

**Comment by johanbrook** [comment]
Is this okay to close, @flippyhead ?

**Comment by flippyhead** [comment]
Sure, thanks!

On Mon, Apr 11, 2016 at 6:55 AM, Johan Brook notifications@github.com
wrote:

> Is this okay to close, @flippyhead https://github.com/flippyhead ?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/lookback/meteor-emails/issues/58#issuecomment-208354819

## 

Peter T. Brown, CTO
Pathable, Inc.
http://pathable.com
