### ISSUE TITLE
make documentation idiot-proof

### ISSUE THREAD

**Issue by chrisbutler** [lookback/meteor-emails#6]
i spent the last 24 hours trying to figure out why the package wasn't working when deployed, only to realize that the routes are only created in development... unfortunately this isn't stated anywhere obvious

it also took me a bit of time to find/figure out the BUNDLE_PATH setting, because it's buried at the bottom. i also had to dig into the code to see how to format it, etc.

do you mind if i take a stab at reformatting the docs a bit? i think i'm not the only one who has been a bit confused

**Comment by johanbrook** [comment]
Thanks for highlighting that, @chrisbutler. On it.

**Comment by johanbrook** [comment]
Added extended documentation in https://github.com/lookback/meteor-emails/commit/d80f8fdce5c3aac5337db139285d66ccf3172bf1.

**Comment by chrisbutler** [comment]
perfect, especially the option to addRoutes. thanks!

**Comment by johanbrook** [comment]
:zap:
