### ISSUE TITLE
Can't update to Meteor 1.3.2.4 - stuck on Downloading lookback:emails

### ISSUE THREAD

**Issue by adamgins** [lookback/meteor-emails#63]
Hi, I can't seem to update my project to Meteor 1.3.2.4 it gets stuck on "Dowloading lookback:emails.."

![screen shot 2016-04-25 at 10 35 41 am](https://cloud.githubusercontent.com/assets/7233741/14771532/a221e970-0ad1-11e6-889b-5ed465e7311d.png)

Any ideas pls?

**Comment by adamgins** [comment]
closing - it worked .. just seemed to takes ages to download.

**Comment by johanbrook** [comment]
Gotcha, thanks for reporting in.
