### ISSUE TITLE
Meteor Accounts Emails

### ISSUE THREAD

**Issue by joshperrin** [lookback/meteor-emails#64]
Is it possible to use this package to override/customize the Meteor accounts emails sent by sendResetPasswordEmail, sendEnrollmentEmail, and sendVerificationEmail?

thanks!

**Comment by johanbrook** [comment]
Hi @joshperrin. Yep, it's possible with the `Mailer.render` function: http://lookback.github.io/meteor-emails/docs/mailer.html#section-12. You'll get back a plain string with which you can attach to the Accounts props. Not sure if they accept HTML though, but I think so.

**Comment by joshperrin** [comment]
Hey @johanbrook thanks for your response. Works great! Is there a way to render the plain text version?

**Comment by johanbrook** [comment]
The `render` function only returns HTML for now. You can use an external npm module to convert HTML to plain text. But we should probably return an object from `render` with both plain text and HTML in the future..
