### ISSUE TITLE
Development directory : invalid regex

### ISSUE THREAD

**Issue by pierrelouisd4j** [lookback/meteor-emails#66]
Hi guys, 
I believe I found a bug in the regex which generate the meteor private directory in development mode.
https://github.com/lookback/meteor-emails/blob/master/lib/utils.js#L28

Indeed, I have a folder in my project containing ".meteor" wich is removed by the regex when the current path is generated.

```
My git dir
|--platform.meteor
   |----some init script
   |----meteor
         |------.meteor
         |------private
```

I know that the short answer is to rename my directory, but fixing this will probably save some time to other people in the future :wink:

**Comment by johanbrook** [comment]
Hi! Sorry for the late reply. Looking into tweaking that regex, would probably involve switching to:

``` js
const meteorRoot = process.cwd().replace(/(^\.meteor.*)/g, '');
```

**Comment by pierrelouisd4j** [comment]
Maybe more something like that :

``` javascript
const meteorRoot = process.cwd().replace(/(\W)(\.meteor.*)/g, '$1');
```

**Comment by johanbrook** [comment]
Right. Are you able to clone down the package repo locally into your `packages` directory and test it out?

**Comment by pierrelouisd4j** [comment]
Hi, I tested this and it seems to work (it's better than my 1st solution)

``` javascript
const reg = new RegExp(path.sep+'\.meteor.*','g');
const meteorRoot = process.cwd().replace(reg, '');
```

**Comment by johanbrook** [comment]
Cool! Fancy filing a PR and I can check it out locally too?

**Comment by pierrelouisd4j** [comment]
#67

**Comment by johanbrook** [comment]
Fixed in https://github.com/lookback/meteor-emails/pull/67.
