### ISSUE TITLE
Feature Request: Include/embed sub-templates

### ISSUE THREAD

**Issue by adamgins** [lookback/meteor-emails#70]
@johanbrook Firstly I love this package, we use it and it's an integral part of our product. Thanks!

I know I asked this before but could not find that old thread... is there a way to include sub templates in a template ala `{{> someTemplateToInclude}}` and if not, is it on the radar or any thoughts of what would be involved in adding it?

A lot of my email templates of some common sub-parts and at the moment I am just duplicating loads of code.

**Comment by johanbrook** [comment]
Thank you!

The server side rendering package which I use doesn't support sub template inclusions, and hence, I can't support it either :/ 

I feel the code duplication angst though. If it's trivial templates (just text) shared helpers which return the same template could work.

https://github.com/meteorhacks/meteor-ssr
