### ISSUE TITLE
TypeError: Mailer.send is not a function

### ISSUE THREAD

**Issue by Noveltysa** [lookback/meteor-emails#73]
On Meteor 1.4.1.1. there is persistent error TypeError: Mailer.send is not a function
when trying to user  Mailer.send() on the server side. Tried  Mailer.sendEmail also same error generated

Although when attempting to call ..http://localhost:4000/emails/send/sample/Peter for example
the error "No testemail or to address specified " is generated, what is the alternative to calling the send url while specifying data params?

**Comment by johanbrook** [comment]
Thanks, I'll have a look.

**Comment by Noveltysa** [comment]
My mistake.. there is nothing wrong with the package,
I did not place Mailer.send within `Meteor.methods({`......
Mailer is working like a charm.. Thanks for your efforts

**Comment by johanbrook** [comment]
Okay :) Thanks.
