### ISSUE TITLE
Names of created routes are not clear

### ISSUE THREAD

**Issue by mcoenca** [lookback/meteor-emails#8]
I was struggling with iron router on how to add the preview and send routes to my onBeforeAction filter.

I think it woud be great add in the docs or in the logs at startup the name, in addtion to the path, of the routes created.

for a template named templateTest, the route name was:
"previewtemplateTestEmail"

that was not obvious, or maybe i missed something !

Thanks,
Best.

**Comment by johanbrook** [comment]
Thanks, @mcoenca. I'll add some docs on that.
