### ISSUE TITLE
Can this be run without Blaze?

### ISSUE THREAD

**Issue by zeroasterisk** [lookback/meteor-emails#83]
This is my only dependency still on blaze... and Blaze results in a fair amount of extra cruft being compiled (time) and sent to the client (waste).

Ideally a system for telling SSR to render with some other toolchain (jade? handlebars?).
Or, some crazy contrivance on telling Blaze to only live on the server (what?).

**Comment by zeroasterisk** [comment]
nevermind - I see that it can be.  sorry (🐑 ish)

**Comment by johanbrook** [comment]
Awesome.

**Comment by zeroasterisk** [comment]
Nope - I was wrong... I can remove `Blaze` from my app, but `meteorhacks:ssr` adds it back, as a dependency, quietly... still sent to client :(

I re-open my question... is there a way to make the SSR library a plugin/utility?

**Comment by johanbrook** [comment]
Gotcha.

Quite a change, since people would need to depend on the SSR lib explicitly. A breaking change, that is. There is sadly no concept of "optional fallback" to the SSR package in a `package.js` file.

**Comment by zeroasterisk** [comment]
Yeah - so it would seem.

I could _maybe_ imagine a split into 3 packages... 
1. which does all the stuff with stubs for the actual SSR
2. which implemented the SSR interface in a standard way
3. a backwards compatible container package tying current functionality together (this package name)

It's a fair amount of work, for not that much gain (none if you're using Blaze). But without it, I will maybe start to roll my own email management suite, which mirrors yours in almost every way... just to save myself the overhead of Blaze for no reason, on every client.

**Comment by johanbrook** [comment]
True. You can easily fork this one too with the power of GitHub, and just pull in upstream changes as they arrive :)

I'll mark this as an enhancement for now. If more people want it, we can look into it.

**Comment by zeroasterisk** [comment]
Ok - this is for sure closed, because it's not a problem with this package.  I tested from nothing and installed in order.  This one does not include blaze client side. It turns out it's core facebook/google accounts, and here's the ticket for it: https://github.com/meteor/meteor/issues/7715
