### ISSUE TITLE
Rendering subTemplates in Templates ``{{>subTemplate}}`` - anyone got this working?

### ISSUE THREAD

**Issue by thebarty** [lookback/meteor-emails#88]
Hi guys,

does anyone know a hack, how to render subTemplates in .html templates??? It seems like ``{{>subTemplate}}`` is NOT supported, which is a same as I'll start keeping it unDRY from know on... damn... 

Any suggestions?

**Comment by johanbrook** [comment]
Sadly, if the meteorhacks:ssr doesn't support it, this package can't either :/ Perhaps switching to Jade as template engine will support it.

**Comment by thebarty** [comment]
Ha, well.. yeah so if we want to stay with Blaze we'd have to officially fork ``meteorhacks:ssr``... sounds like a fun and time-intensive thing to do! :-/ Right now I plan to stay with Blaze so no need for Jade... 👍

**Comment by thebarty** [comment]
seems like there even is an existing fork https://github.com/meteorhacks/meteor-ssr/pull/40#issue-124286924, which has NOT been included... it just lies around there since dez 2015

**Comment by thebarty** [comment]
Since meteorhacks is NOT developed anymore, how about fetching it into the lookback package (including the pull-request from above)... so we have it in "our codebase" and complete control?

**Comment by johanbrook** [comment]
I or Lookback have no immediate need for sub-templates right now, so feel free to pull down this package at your end and experiment with the changes you're suggesting :) And then submit a PR if everything works smoothly, and I'll have a look at it.

**Comment by thebarty** [comment]
Ok, i might give it a go, but only after I experience 3 times in my code repeating myself. :-O

Which way would you recon? I guess the most elegant way would be to create a fork of meteorhacks:ssr and publish it as an athmosphere package and then make it a dependence in lookback?

**Comment by johanbrook** [comment]
Since the SSR package hasn't (or won't likely) get any updates, I think it's safe to fork it into a new package, yes. Make sure that feature branch is update with `master` of the SSR package, etc.

**Comment by thebarty** [comment]
OK, I found a way to do this without too much work:

 1) create 1 file per subtemplate within /private/*
 2) compile the subtemplate (and give it a name) by `SSR.compileTemplate('subTemplate', Assets.getText('test_subtemplate.html'))`
 3) use it within your main template via "{{>subTemplate data=dataContext}}"

Of course it would be really cool to support this with standard blaze-style, BUT it works for now.

@johanbrook: Thanks again for your help!

**Comment by johanbrook** [comment]
Cool!
