### ISSUE TITLE
Using multiple blaze templates for one email

### ISSUE THREAD

**Issue by dbaruchel** [lookback/meteor-emails#9]
Hi ! 
Thanks for the package,
I've been trying to use multiple templates when designing my email (so I do not have to repeat the html code) but I keep getting a "no such template" error:

This is my code in private/activity_email/report.html:

``` html
<body>
<tbody>
  {{>MailHeader}}
  {{>MailSocial}}
  {{>MailActivities}}
 </tbody>
 </body>

<template name="MailHeader">
...
</template>
<template name="MailSocial">
...
</template>
<template name="MailActivities">
...
</template>
```

in server/newsletter/template.js

``` javascript
EmailTemplates = {};

EmailTemplates.activityReport  = {
  path: 'activity_emails/report.html',
  scss: 'activity_emails/report.scss',
  helpers:{
    userName: function () {
      return this.user.username;
    }
  },
  route:{
    path: '/activity_report_email/:user',
    data: function() {
      return {user: Meteor.users.findOne(this.params.user)};
    }
  }
};

```

in server/newsletter/config.js

``` javascript
Meteor.startup(function(){
    Mailer.config({
        from: '...'
        testEmail: '...'
    });

    Mailer.init({
      templates: EmailTemplates,
      helpers: {}
    });
});
```

I did not understand (sorry, quite new to this) if it was possible or not,
Thanks

**Comment by johanbrook** [comment]
Hi @dbaruchel! 

I'm using https://github.com/meteorhacks/meteor-ssr/ under the hood to render the templates, and afaik it doesn't support nesting/partials in templates yet (see previous issue here: https://github.com/lookback/meteor-emails/issues/5).
